name = "GeometricDistributions"
uuid = "b20d70ac-1ced-44b6-8f67-cab24d52ea6c"
authors = ["Joaquín Rodríguez <joaq.rod0@gmail.com>"]
version = "0.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
LinearAlgebra = "1.11.0"
Random = "1.11.0"
